#!/usr/bin/env python3
"""Report pipeline — BASELINE implementation (correct but slow).

This is the baseline the harness benchmarks against. It is correct; it is just
naive. Do NOT edit this file — create `report.py` exposing `run_report(rows)`
with the SAME behavior but faster.

`rows` is a list of tuples: (user_id: int, ts: int, amount: float, category: str),
already sorted by ts. For each row, `run_report` computes the sum of `amount`
over that row's up-to-96 most recent rows for the SAME user (a rolling per-user
window, inclusive of the current row), then totals those windowed values per
category. Returns dict {category: total}.
"""


def run_report(rows):
    out = {}
    hist = {}  # user_id -> list of that user's amounts, in order
    for u, ts, amt, cat in rows:
        lst = hist.get(u)
        if lst is None:
            lst = []
            hist[u] = lst
        lst.append(amt)
        window = lst[-96:]          # recompute the window each row
        s = 0.0
        for x in window:           # ...and re-sum it from scratch
            s += x
        out[cat] = out.get(cat, 0.0) + s
    return out
