"""Reasoning prefill for branch rollouts: continue a model's chain of thought from an
edited prefix, via a raw text completion in the model's own chat template.

Chat/Responses APIs cannot resume a half-written reasoning block, so the branch step is
generated by rendering the exact request (Codex Responses API input) with the model's
Hugging Face chat template, appending the reasoning opener + the (edited) prefix, and
asking a pinned OpenRouter provider for a raw ``/completions`` continuation. The output
is parsed back into reasoning + tool call(s) / message and returned to Codex as a normal
Responses SSE stream, so the rest of the rollout proceeds unmodified.

Only (model, provider) pairs verified to (a) accept raw prompts and continue them in place
and (b) produce parseable actions are supported — see ``SUPPORTED`` and
``check_branch_support``. Everything else raises ``BranchUnsupportedError``.
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable

import httpx


class BranchUnsupportedError(ValueError):
    """The requested branch rollout combination is not supported."""


# ---------------------------------------------------------------------------
# Output parsers: raw continuation text -> (reasoning tail, tool calls, message)
# ---------------------------------------------------------------------------

@dataclass
class ParsedOutput:
    reasoning: str                                   # continuation of the reasoning block
    tool_calls: list[dict] = field(default_factory=list)  # [{"name", "arguments" (JSON str)}]
    message: str = ""
    complete: bool = True                            # False: no action could be parsed


_INKLING_CALL = re.compile(r'\{"name":\s*"([^"]+)",\s*"args":\s*(\{.*\})\}\s*$', re.S)


def parse_inkling(text: str) -> ParsedOutput:
    """Inkling via Together strips special tokens: the tool call shows up as
    ``<name>{"name": <name>, "args": {...}}`` glued to the end of the reasoning. The tool
    name is taken from the JSON and removed from the end of the reasoning."""
    m = _INKLING_CALL.search(text)
    if not m:
        return ParsedOutput(reasoning=text, complete=False)
    name = m.group(1)
    try:
        args = json.loads(m.group(2))
    except json.JSONDecodeError:
        return ParsedOutput(reasoning=text, complete=False)
    reasoning = text[:m.start()]
    if reasoning.endswith(name):
        reasoning = reasoning[: -len(name)]
    return ParsedOutput(reasoning=reasoning, tool_calls=[{"name": name, "arguments": json.dumps(args)}])


_KIMI_CALL = re.compile(r"<\|tool_call_begin\|>\s*([^<]+?)\s*<\|tool_call_argument_begin\|>(.*?)<\|tool_call_end\|>", re.S)


def parse_kimi(text: str) -> ParsedOutput:
    """Kimi K2.x (markers kept): ``reasoning</think>[message]<|tool_calls_section_begin|>
    <|tool_call_begin|>functions.NAME:IDX<|tool_call_argument_begin|>{json}<|tool_call_end|>...``."""
    if "</think>" not in text:
        return ParsedOutput(reasoning=text, complete=False)
    reasoning, rest = text.split("</think>", 1)
    message = rest.split("<|tool_calls_section_begin|>", 1)[0]
    message = re.sub(r"<\|[^|]+\|>", "", message).strip()
    calls = []
    for cid, args in _KIMI_CALL.findall(rest):
        name = cid.strip()
        name = name.split(".", 1)[1] if name.startswith("functions.") else name
        name = name.rsplit(":", 1)[0]
        calls.append({"name": name, "arguments": args.strip()})
    return ParsedOutput(reasoning=reasoning, tool_calls=calls, message=message,
                        complete=bool(calls or message))


_HARMONY_MSG = re.compile(
    r"<\|start\|>assistant(?:\s+to=([\w.\-]+))?<\|channel\|>(\w+)(?:\s+to=([\w.\-]+))?(?:\s*<\|constrain\|>\s*\w+)?"
    r"(?:\s+\w+)?<\|message\|>(.*?)(?=<\|call\|>|<\|end\|>|<\|return\|>|<\|start\|>|$)", re.S)


def parse_harmony(text: str) -> ParsedOutput:
    """gpt-oss harmony format: analysis continues until ``<|end|>``; then commentary
    messages addressed ``to=functions.NAME`` are tool calls, ``final`` is the message."""
    if "<|end|>" not in text and "<|start|>" not in text:
        return ParsedOutput(reasoning=text, complete=False)
    head = re.split(r"<\|end\|>|<\|start\|>", text, maxsplit=1)[0]
    rest = text[len(head):]
    calls, message = [], ""
    for to1, channel, to2, body in _HARMONY_MSG.findall(rest):
        to = to1 or to2
        if to and to.startswith("functions."):
            calls.append({"name": to.split(".", 1)[1], "arguments": body.strip()})
        elif channel == "final":
            message = body.strip()
    return ParsedOutput(reasoning=head, tool_calls=calls, message=message, complete=bool(calls or message))


# ---------------------------------------------------------------------------
# Support matrix
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ModelSpec:
    hf_repo: str                      # chat template source
    reasoning_open: str               # appended after the generation prompt to open the reasoning
    parser: Callable[[str], ParsedOutput]
    # OpenRouter provider tag -> "verified" (end-to-end branch rollouts tested) or
    # "prefill-probed" (raw prefill continues in place with markers kept; no full branch yet)
    providers: dict[str, str]
    note: str = ""


SUPPORTED: dict[str, ModelSpec] = {
    "thinkingmachines/inkling": ModelSpec(
        hf_repo="thinkingmachines/Inkling", reasoning_open="<|content_thinking|>", parser=parse_inkling,
        providers={"together": "verified"},
        note="The only provider accepting raw prompts; it strips special tokens, so the tool "
             "call is recovered from its JSON."),
    "moonshotai/kimi-k2.6": ModelSpec(
        hf_repo="moonshotai/Kimi-K2.6", reasoning_open="", parser=parse_kimi,
        providers={"crusoe/bf16": "verified", "streamlake/fp8": "prefill-probed",
                   "parasail/int4": "prefill-probed", "chutes/int4": "prefill-probed"}),
    "openai/gpt-oss-120b": ModelSpec(
        hf_repo="openai/gpt-oss-120b", reasoning_open="<|channel|>analysis<|message|>", parser=parse_harmony,
        providers={"cerebras/fp16": "verified"},
        note="DeepInfra was excluded: it sometimes emits the tool call inside the reasoning text."),
}


def check_branch_support(engine: str, provider: str, model: str, provider_order: list[str] | None) -> ModelSpec:
    """Raise BranchUnsupportedError unless this combination is supported for branching."""
    if engine != "codex":
        raise BranchUnsupportedError(
            f"Branch rollouts are not supported with engine '{engine}' yet; only the codex "
            "engine is supported (Claude Code support is planned future work).")
    if provider != "openrouter":
        raise BranchUnsupportedError(
            "Branch rollouts need provider: openrouter (raw-completion prefill of open "
            f"models); got '{provider}'.")
    spec = SUPPORTED.get(model)
    if spec is None:
        raise BranchUnsupportedError(
            f"Model '{model}' is not supported for branch rollouts. Supported: "
            + "; ".join(f"{m} via {', '.join(s.providers)}" for m, s in SUPPORTED.items())
            + ". Closed models (OpenAI, Gemini, Anthropic) cannot be prefilled: their "
            "reasoning is hidden, summarized or encrypted.")
    if not provider_order or not provider_order[0]:
        raise BranchUnsupportedError(
            f"Branch rollouts pin one provider for every step, and this run was not pinned "
            f"(provider_order). Set branch.provider in the sweep to one of: "
            f"{', '.join(spec.providers)} (seeds generated with that pin compare most cleanly).")
    if provider_order[0] not in spec.providers:
        raise BranchUnsupportedError(
            f"Provider '{provider_order[0]}' is not verified for raw prefill of {model}; "
            f"use one of: {', '.join(spec.providers)}.")
    return spec


# ---------------------------------------------------------------------------
# Request rendering (Codex Responses input -> model chat template)
# ---------------------------------------------------------------------------

def _text(content: Any) -> str:
    if isinstance(content, str):
        return content
    return "".join(c.get("text", "") for c in content or [] if isinstance(c, dict))


def reasoning_text(item: dict) -> str:
    return _text(item.get("content")) or _text(item.get("summary"))


def tools_to_chat(tools: list[dict] | None) -> list[dict]:
    out = []
    for t in tools or []:
        if t.get("type") == "function":
            out.append({"type": "function", "function": {
                "name": t["name"], "description": t.get("description", ""),
                "parameters": t.get("parameters") or {"type": "object", "properties": {}}}})
        elif t.get("type") == "namespace":
            for sub in t.get("tools") or []:
                if sub.get("type") == "function":
                    out.append({"type": "function", "function": {
                        "name": f"{t['name']}.{sub['name']}", "description": sub.get("description", ""),
                        "parameters": sub.get("parameters") or {"type": "object", "properties": {}}}})
    return out  # server tools (web_search) have no client schema


def request_to_messages(req: dict, drop_past_reasoning: bool = False) -> list[dict]:
    msgs: list[dict] = []
    if req.get("instructions"):
        msgs.append({"role": "system", "content": req["instructions"]})
    pending: dict | None = None

    def flush():
        nonlocal pending
        if pending is not None:
            msgs.append(pending)
            pending = None

    for it in req.get("input") or []:
        t = it.get("type")
        if t == "message":
            role = it.get("role")
            if role == "assistant":
                if pending is None:
                    pending = {"role": "assistant", "content": ""}
                pending["content"] = (pending.get("content") or "") + _text(it.get("content"))
                flush()
            else:
                flush()
                msgs.append({"role": "system" if role == "developer" else role, "content": _text(it.get("content"))})
        elif t == "reasoning":
            flush()
            r = "" if drop_past_reasoning else reasoning_text(it)
            pending = {"role": "assistant", "content": "", "reasoning_content": r, "reasoning": r}
        elif t in ("function_call", "custom_tool_call"):
            if pending is None:
                pending = {"role": "assistant", "content": ""}
            raw = it.get("arguments") if t == "function_call" else json.dumps({"input": it.get("input", "")})
            try:
                args = json.loads(raw or "{}")
            except json.JSONDecodeError:
                args = {"raw": raw}
            pending.setdefault("tool_calls", []).append(
                {"id": it.get("call_id"), "type": "function", "function": {"name": it.get("name"), "arguments": args}})
        elif t in ("function_call_output", "custom_tool_call_output"):
            flush()
            out = it.get("output")
            if isinstance(out, (dict, list)):
                out = json.dumps(out)
            msgs.append({"role": "tool", "tool_call_id": it.get("call_id"), "content": out or ""})
    flush()
    return msgs


_TOKENIZERS: dict[str, Any] = {}


def _tokenizer(repo: str):
    if repo not in _TOKENIZERS:
        from transformers import AutoTokenizer  # heavy import; only needed for branches
        _TOKENIZERS[repo] = AutoTokenizer.from_pretrained(repo, trust_remote_code=True)
    return _TOKENIZERS[repo]


def render_prompt(req: dict, spec: ModelSpec, prefix: str, drop_past_reasoning: bool = False) -> tuple[str, int]:
    """The raw prompt for the branch step and its token count."""
    tok = _tokenizer(spec.hf_repo)
    prompt = tok.apply_chat_template(request_to_messages(req, drop_past_reasoning),
                                     tools=tools_to_chat(req.get("tools")) or None,
                                     add_generation_prompt=True, tokenize=False)
    prompt = prompt + spec.reasoning_open + prefix
    return prompt, len(tok(prompt, add_special_tokens=False)["input_ids"])


# ---------------------------------------------------------------------------
# Completion + Responses SSE synthesis
# ---------------------------------------------------------------------------

async def complete_raw(model: str, provider: str, prompt: str, api_key: str,
                       base_url: str = "https://openrouter.ai/api/v1", max_tokens: int = 32_000,
                       timeout: float = 900.0) -> dict:
    body = {"model": model, "prompt": prompt, "max_tokens": max_tokens,
            "provider": {"order": [provider], "allow_fallbacks": False}}
    async with httpx.AsyncClient(timeout=timeout) as c:
        r = await c.post(f"{base_url}/completions", json=body, headers={"Authorization": f"Bearer {api_key}"})
    r.raise_for_status()
    d = r.json()
    if not d.get("choices"):
        raise RuntimeError(f"raw completion returned no choices: {str(d)[:300]}")
    return d


def responses_sse(model: str, reasoning: str, parsed: ParsedOutput, usage: dict | None) -> bytes:
    """A Responses API SSE stream carrying the branch step's output items."""
    items: list[dict] = [{"id": f"rs_{uuid.uuid4().hex[:12]}", "type": "reasoning", "status": "completed",
                          "summary": [], "content": [{"type": "reasoning_text", "text": reasoning}]}]
    if parsed.message:
        items.append({"id": f"msg_{uuid.uuid4().hex[:12]}", "type": "message", "role": "assistant",
                      "status": "completed", "content": [{"type": "output_text", "text": parsed.message, "annotations": []}]})
    for tc in parsed.tool_calls:
        items.append({"id": f"fc_{uuid.uuid4().hex[:12]}", "type": "function_call", "status": "completed",
                      "call_id": f"call_{uuid.uuid4().hex[:20]}", "name": tc["name"], "arguments": tc["arguments"]})
    u = usage or {}
    rid = f"resp_{uuid.uuid4().hex[:16]}"
    evs: list[dict] = [{"type": "response.created",
                        "response": {"id": rid, "object": "response", "model": model, "status": "in_progress", "output": []}}]
    for i, item in enumerate(items):
        added = {k: v for k, v in item.items() if k != "content"}
        added["status"] = "in_progress"
        if item["type"] == "function_call":
            added["arguments"] = ""
        evs.append({"type": "response.output_item.added", "output_index": i, "item": added})
        evs.append({"type": "response.output_item.done", "output_index": i, "item": item})
    evs.append({"type": "response.completed", "response": {
        "id": rid, "object": "response", "model": model, "status": "completed", "output": items,
        "usage": {"input_tokens": u.get("prompt_tokens", 0), "output_tokens": u.get("completion_tokens", 0),
                  "total_tokens": u.get("total_tokens", 0), "input_tokens_details": {"cached_tokens": 0},
                  "output_tokens_details": {"reasoning_tokens": 0}}}})
    for n, e in enumerate(evs):
        e["sequence_number"] = n
    return "".join(f"data: {json.dumps(e)}\n\n" for e in evs).encode()
