#!/usr/bin/env python3
"""Bin-packing solver — BASELINE implementation (correct but weak).

This is the baseline the harness benchmarks against. It produces valid packings;
it just uses more bins than necessary. Do NOT edit this file — create `solver.py`
exposing `solve(items, capacity)` that returns a valid packing using FEWER bins.

`items` is a list of positive ints (item sizes); `capacity` is a positive int.
`solve` returns a list of bins, each bin a list of item INDICES (into `items`).
A packing is VALID iff every index 0..len(items)-1 appears exactly once and no
bin's item-size total exceeds `capacity`. The objective is the number of bins
(fewer is better).
"""


def solve(items, capacity):
    # Next-fit: keep one open bin; start a new one whenever the next item doesn't fit.
    bins = []
    cur = []
    cur_load = 0
    for i, size in enumerate(items):
        if cur and cur_load + size > capacity:
            bins.append(cur)
            cur = []
            cur_load = 0
        cur.append(i)
        cur_load += size
    if cur:
        bins.append(cur)
    return bins
